### ISSUE TITLE
破解失败

### ISSUE THREAD

**Issue by Zhaolei2008** [Tao0Lu/ArkNightsForMinor#10]
不知道为什么,用大佬的方法破解1.5.81版本失败了,望解答(全部按照大佬的方法弄得,一点也没有错)

**Comment by long45343** [comment]
> 不知道为什么,用大佬的方法破解1.5.81版本失败了,望解答(全部按照大佬的方法弄得,一点也没有错)

已经有现成的了
你还要注意一下架构

**Comment by Zhaolei2008** [comment]
那大佬考虑过做B服的破解吗，我弄了一周没弄出来
