### ISSUE TITLE
（能不能帮忙写个hosts

### ISSUE THREAD

**Issue by long45343** [Tao0Lu/ArkNightsForMinor#4]
垃圾广电宽带
可不可以把这游戏的地址写成hosts
我看看能不能解决这游戏加载奇慢甚至GG的问题

**Comment by Tao0Lu** [comment]
我觉得应该不是Hosts的问题吧
![QQ截图20210823152941](https://user-images.githubusercontent.com/35399423/130407795-f1be8216-f9b7-49d1-b501-824699f1d945.png)

**Comment by long45343** [comment]
（官网永远上的去
问题是在游戏登录和加载时总是会卡住甚至无法加载（
论垃圾广电到底对联通的CDN做了什么手脚（

**Comment by Tao0Lu** [comment]
203.107.45.244 ak-gs-gf.hypergryph.com
203.107.45.244 as.hypergryph.com
203.107.45.244 ak-conf.hypergryph.com
1.1.1.1 解析出来都是一样的（）

**Comment by long45343** [comment]
> 203.107.45.244 ak-gs-gf.hypergryph.com
> 203.107.45.244 as.hypergryph.com
> 203.107.45.244 ak-conf.hypergryph.com
> 1.1.1.1 解析出来都是一样的（）

广电锁死了我的dns啊啊啊啊（
天晓得它是怎么做到的
改了跟没改一样

**Comment by Tao0Lu** [comment]
你可以在mitmproxy中写个脚本，访问 as.hypergryph.com 前跳转 203.107.45.244 并保留请求头中的 Host:as.hypergryph.com（跟doh一样）
