### ISSUE TITLE
月卡问题

### ISSUE THREAD

**Issue by kiang12** [Tao0Lu/ArkNightsForMinor#6]
之前yj补偿了防沉迷的月卡，现在我领取防沉迷期间的月卡会不会封号？

**Comment by kiang12** [comment]
> 之前yj补偿了防沉迷的月卡，现在我领取防沉迷期间的月卡会不会封号？

**Comment by leisiyu1** [comment]
不知道欸（
领就对了，封号再说（原来发现白嫖的不止我一个）
